apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
  labels:
    app.kubernetes.io/name: order
    app: order
data:
  SERVER_PORT: "8089"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "https://mcart.space"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://mcart-pg-postgresql.mcart.svc.cluster.local:5432/order"
  SPRING_DATASOURCE_USERNAME: "order_user"
  SPRING_DATASOURCE_PASSWORD: "MY_PASSWORD"
  ORDER_CART_BASE_URL: "http://cart.mcart.svc.cluster.local"
  ORDER_INVENTORY_BASE_URL: "http://inventory.mcart.svc.cluster.local"
  ORDER_PAYMENT_BASE_URL: "http://payment.mcart.svc.cluster.local"
  ORDER_PRODUCT_BASE_URL: "http://product.mcart.svc.cluster.local"
  ORDER_USER_BASE_URL: "http://user.mcart.svc.cluster.local:8082"
  SPRING_CLOUD_GCP_PROJECT_ID: "ecommerce-491019"
  SPRING_CLOUD_GCP_PUBSUB_ENABLED: "true"
  ORDER_PUBSUB_ENABLED: "true"
  ORDER_PUBSUB_TOPIC: "order-paid-events"
