apiVersion: v1
kind: ServiceAccount
metadata:
  name: order
  labels:
    app.kubernetes.io/name: order
    app: order
  annotations:
    iam.gke.io/gcp-service-account: mcart-order@ecommerce-491019.iam.gserviceaccount.com
