apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  labels:
    app: user
data:
  SERVER_PORT: "8082"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresql.user.svc.cluster.local:5432/user"
  SPRING_DATASOURCE_USERNAME: "user_user"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "https://mcart.space"
  SPRING_CLOUD_GCP_PROJECT_ID: "ecommerce-491019"
  SPRING_CLOUD_GCP_PUBSUB_ENABLED: "true"
  USER_PUBSUB_ENABLED: "true"
  USER_PUBSUB_SUBSCRIPTION: "user-signup-events-sub"
