apiVersion: v1
kind: Service
metadata:
  name: user
  annotations:
    cloud.google.com/backend-config: '{"default":"user-bc"}'
  labels:
    app: user
spec:
  type: ClusterIP
  selector:
    app: user
  ports:
    - name: http
      port: 8082
      targetPort: http
      protocol: TCP
