apiVersion: v1
kind: ConfigMap
metadata:
  name: search-config
  labels:
    app: search
data:
  SERVER_PORT: "8083"
  SPRING_APPLICATION_NAME: "search"
  SPRING_ELASTICSEARCH_URIS: "http://elasticsearch.elasticsearch.svc.cluster.local:9200"
  APP_SECURITY_ENABLED: "true"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "https://auth.example.com"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
