# Copy to secret.yaml when Elasticsearch uses auth (match values-elasticsearch). kubectl apply -n mcart -f secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: search-secrets
  labels:
    app: search
type: Opaque
stringData:
  SPRING_ELASTICSEARCH_USERNAME: elastic
  SPRING_ELASTICSEARCH_PASSWORD: MY_PASSWORD
