apiVersion: v1
kind: ConfigMap
metadata:
  name: mcart-ui-config
  labels:
    app.kubernetes.io/name: mcart-ui
    app.kubernetes.io/component: frontend
data:
  NODE_ENV: "production"
  PORT: "4000"
  NG_ALLOWED_HOSTS: "localhost,mcart.space,www.mcart.space"
  API_BASE_URL: "https://mcart.space"
