apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory
  labels:
    app.kubernetes.io/name: inventory
    app: inventory
  annotations:
    iam.gke.io/gcp-service-account: mcart-inventory@ecommerce-491019.iam.gserviceaccount.com
