apiVersion: v1
kind: Service
metadata:
  name: inventory
  labels:
    app.kubernetes.io/name: inventory
    app: inventory
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: inventory
    app: inventory
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
