apiVersion: v1
kind: ConfigMap
metadata:
  name: email-config
  labels:
    app: email
data:
  SERVER_PORT: "8090"
  SPRING_CLOUD_GCP_PROJECT_ID: "ecommerce-491019"
  SPRING_CLOUD_GCP_PUBSUB_ENABLED: "true"
  EMAIL_PUBSUB_ENABLED: "true"
  EMAIL_PUBSUB_SUBSCRIPTION: "email-verification-events-sub"
  EMAIL_ORDER_PAID_ENABLED: "true"
  EMAIL_ORDER_PAID_SUBSCRIPTION: "order-paid-email-sub"
  EMAIL_ORDER_BASE_URL: "https://mcart.space"
  REDIS_HOST: "mcart-redis-master.mcart.svc.cluster.local"
  REDIS_PORT: "6379"
  SPRING_MAIL_HOST: "smtp.gmail.com"
  SPRING_MAIL_PORT: "587"
  SPRING_MAIL_SSL_TRUST: "smtp.gmail.com"
