apiVersion: v1
kind: ServiceAccount
metadata:
  name: product
  labels:
    app.kubernetes.io/name: product
    app.kubernetes.io/version: "0.0.1"
  annotations:
    iam.gke.io/gcp-service-account: mcart-product@ecommerce-491019.iam.gserviceaccount.com
