# Annotate for Workload Identity after you create the GCP service account:
#   iam.gke.io/gcp-service-account: mcart-product@PROJECT_ID.iam.gserviceaccount.com
apiVersion: v1
kind: ServiceAccount
metadata:
  name: product
  labels:
    app.kubernetes.io/name: product
    app.kubernetes.io/version: "0.0.1"
