apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-indexer
  labels:
    app.kubernetes.io/name: product-indexer
    app.kubernetes.io/version: "0.0.1"
  annotations:
    iam.gke.io/gcp-service-account: mcart-product-indexer@ecommerce-491019.iam.gserviceaccount.com
