apiVersion: v1
kind: Service
metadata:
  name: product-indexer
  annotations:
    cloud.google.com/backend-config: '{"default":"product-indexer-bc"}'
  labels:
    app.kubernetes.io/name: product-indexer
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: product-indexer
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
