apiVersion: v1
kind: Service
metadata:
  name: auth
  annotations:
    cloud.google.com/backend-config: '{"default":"auth-bc-v2"}'
  labels:
    app: auth
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - name: http
      port: 8081
      targetPort: http
      protocol: TCP
